project:
  type: website

website:
  title: "codecelloptions"
  reader-mode: true
  repo-url: https://github.com/coatless-quarto/codecelloptions/
  repo-actions: [edit, issue]
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/coatless-quarto/codecelloptions/
    contents: 
      - text: "Home"
        file: index.qmd
      - section: "Support"
        contents:
        - text: "Submit an issue"
          href: https://github.com/coatless-quarto/codecelloptions/issues/new/choose
